// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAKurMQigsVGK20zNuYQ6jDiBQH9VdFhs',
    appId: '1:503181496239:web:20365011082c5f3cc6e95a',
    messagingSenderId: '503181496239',
    projectId: 'city-guide-firebase-a12d7',
    authDomain: 'city-guide-firebase-a12d7.firebaseapp.com',
    storageBucket: 'city-guide-firebase-a12d7.appspot.com',
    measurementId: 'G-6VE6C8FJ65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ6cNxGaslTw-aqUELPWg-fbsa5--fVA8',
    appId: '1:503181496239:android:fcafe9ec940fd735c6e95a',
    messagingSenderId: '503181496239',
    projectId: 'city-guide-firebase-a12d7',
    storageBucket: 'city-guide-firebase-a12d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6uw3a49-0c1jOjQT2JN57ITh6Ib1AXBc',
    appId: '1:503181496239:ios:8da6b36012d46037c6e95a',
    messagingSenderId: '503181496239',
    projectId: 'city-guide-firebase-a12d7',
    storageBucket: 'city-guide-firebase-a12d7.appspot.com',
    iosClientId: '503181496239-3tdriav3k6i28sunfhss4fv1bja34ama.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityGuideFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6uw3a49-0c1jOjQT2JN57ITh6Ib1AXBc',
    appId: '1:503181496239:ios:8da6b36012d46037c6e95a',
    messagingSenderId: '503181496239',
    projectId: 'city-guide-firebase-a12d7',
    storageBucket: 'city-guide-firebase-a12d7.appspot.com',
    iosClientId: '503181496239-3tdriav3k6i28sunfhss4fv1bja34ama.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityGuideFirebase',
  );
}
